### ISSUE TITLE
Generate change log between 2 specific tags

### ISSUE THREAD

**Issue by skywinder** [skywinder/github-changelog-generator#172]
@jspahrsummers comment:

>Is there a way to do this between arbitrary commits? I sometimes create tags before writing the release notes, so it'd be nice to create a changelog for “between tag A and tag B.”

https://github.com/Mantle/Mantle/pull/468#issuecomment-84247797

**Comment by estahn** [comment]
@skywinder It would be great if the generator doesn't replace the entire file but just adds missing versions. We have some manual added information which we don't want to lose when generating the changelog.

**Comment by skywinder** [comment]
@estahn Yes, I'm also thinking about this option. But it's pretty unclear, how to implement it. Please, create another issue with description of this feature-request, and we are discuss how to do it better.

**Comment by estahn** [comment]
@skywinder I created a new issue (#209) with some implementation ideas.

**Comment by skywinder** [comment]
Implemented in `1.5.0`. Use `--between-tags` option to specify tags.

**Comment by espears4sq** [comment]
@skywinder The original quote for this issue asks for the feature to work between commits, but it seems that this only works between tags (at least when I use `--between-tags` and provide commit hash IDs, it always says it cannot find them).

Is there a way to do this between any two arbitrary commits, even if they have no relationship to any tags? It would be fine if assumptions need to be made about the commits existing in the same branch or in master, etc., and arbitrary failures if the assumptions aren't met... but the requirement that it can only works with actual tags would not be usable in my situation (a repo where tags and releases are not permitted, and changelog only makes sense between commits in master).
