### ISSUE TITLE
Changelog for Private Repository

### ISSUE THREAD

**Issue by bernamaxim** [skywinder/github-changelog-generator#206]
How I can generate changelog for private repository?
I just generate it and the output only :

# Change Log

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by uncleserb** [comment]
I'm getting the exact same issue here ;)

**Comment by skywinder** [comment]
Please, provide command line, that you execute. For which repo are you try to generate change log?

**Comment by uncleserb** [comment]
Output is exactly as mentioned above by @bernamaxim. Command line is:

```
github_changelog_generator -t ************
```

**Comment by sneal** [comment]
Private repositories work fine, just make sure you provide an OAuth token so its accessible. I've also noticed the same output on a small public repo I have that doesn't have any tags.

**Comment by skywinder** [comment]
@uncleserb I mean output, that script prints to console.

**Comment by ryanmoon** [comment]
I get something like this for console output:
```
Detected user:foo, project:bar
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :exclude_labels=>["duplicate", "question", "invalid", "wontfix"],
 :pulls=>true,
 :issues=>true,
 :verbose=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :author=>true,
 :filter_issues_by_milestone=>true,
 :compare_link=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :branch=>"origin",
 :user=>"foo",
 :project=>"bar"}

Found 0 tags
Received issues: 5
Fetching merged dates... Done!
Filtered pull requests: 3
Filtered issues: 2
Fetching events for issues and PR: Done!
Fetching closed dates for issues: Done!
Fetching tags: Done!
Sorting tags..
Generating log..
Done!
Generated log placed in /Users/foo/Documents/bar/CHANGELOG.md
```

Which will output a CHANGELOG similar to what @bernamaxim reported.

**Comment by bernamaxim** [comment]
Same exactly with my issue.

**Comment by bernamaxim** [comment]
And I have been make sure to provide an 0Auth with token.

Same exactly with my issue.

**Comment by uncleserb** [comment]
Same output on my side with a private repo:

```
Detected user:xxx, project:zzz
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :exclude_labels=>["duplicate", "question", "invalid", "wontfix"],
 :pulls=>true,
 :issues=>true,
 :verbose=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :author=>true,
 :filter_issues_by_milestone=>true,
 :compare_link=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :branch=>"origin",
 :token=>"yyyyyyyyyy",
 :user=>"xxx",
 :project=>"zzz"}

Found 0 tags                   
Received issues: 74            
Fetching merged dates... Done!                     
Filtered pull requests: 0
Filtered issues: 72
Fetching events for issues and PR: Done!                    
Fetching closed dates for issues: Done!
Fetching tags: Done!             
Sorting tags..
Generating log..
Done!
Generated log placed in /Users/xxx/Documents/zzz/CHANGELOG.md
```

**Comment by skywinder** [comment]
> Found 0 tags   

It seems, that you don't have any tags in your repo! @sneal was right.
You should push them before run the script:
    git push origin --tags

**Comment by uncleserb** [comment]
Very odd: I do have tags on my test issues; see below screen grab:
![changelog-generator-issue-tags](https://cloud.githubusercontent.com/assets/1575503/6801133/7a4fe662-d225-11e4-9e68-880f585de7fd.png)

Couldn't that be the culprit (tags in private repos not being read / parsed correctly)?

**Comment by skywinder** [comment]
@uncleserb The `Later` is not a tag. It's a milestone. It's similar, but not the same this as tags.
Milestones it's pure GitHub feature, and tag is a built-in git feature. You can look at the tags in main page, for example, for this repo: 
![screen shot 2015-03-24 at 14 04 09](https://cloud.githubusercontent.com/assets/3356474/6801242/bd61f7a2-d22e-11e4-8384-ffbac9c1078a.png)

All you need is mark by **Lightweight Tag** specific commit. And push them to remote repo.
More info, how to do it there: http://git-scm.com/book/en/v2/Git-Basics-Tagging

Example:

    git checkout 3c4ba4
    git tag v1.2.3
    g push --tags

**Comment by uncleserb** [comment]
Fair enough ;) Sorry about that. Will give it another go and close this if it works. Thanks!

**Comment by uncleserb** [comment]
Tested and worked fine; the changelog generator works fine with private repos! Sorry about the nuisance ;)

**Comment by skywinder** [comment]
@uncleserb glad to hear it :rocket:
