### ISSUE TITLE
Change "Full Changelog" for each commit reference

### ISSUE THREAD

**Issue by Kikobeats** [skywinder/github-changelog-generator#215]
I Love this project. At this moment I use a similar tooo called [changelog-maker](https://github.com/rvagg/changelog-maker) that scan a git project and create a reference in Markdown for of each commit.

What do you think to do something similar instead of just put Full Changelog message?

You can check an example of changelog using changelog-maker [here](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#commits)

**Comment by skywinder** [comment]
Hi. Thanks for mention it.  :+1: 

I think it's similar to #51. So, I close it in favour of that issue.

Feel free to explain your suggestions about style, how to implement this feature there.

**Comment by Kikobeats** [comment]
Perfect! :-)
