### ISSUE TITLE
Escape ` in PR titles

### ISSUE THREAD

**Issue by vassilevsky** [skywinder/github-changelog-generator#224]
I used this gem to generate a changelog for https://github.com/gemhome/rmagick .
It has this PR: https://github.com/gemhome/rmagick/pull/172
Generated changelog item:

```
- fix: in `require': cannot load such file -- rmagick/version \(LoadError\) [\#172](https://github.com/gemhome/rmagick/pull/172) ([u338steven](https://github.com/u338steven))
```

I believe ` breaks formatting.

**Comment by skywinder** [comment]
The result of generation for this issue:

- fix: in `require': cannot load such file -- rmagick/version \(LoadError\) [\#172](https://github.com/gemhome/rmagick/pull/172) ([u338steven](https://github.com/u338steven))

It seems, it looks as should be.
What the expected result for this string?

**Comment by skywinder** [comment]
Related with #34.

**Comment by vassilevsky** [comment]
Here's how it looks like in Vim (I use [Janus](https://github.com/carlhuda/janus) config):
![backtick](https://cloud.githubusercontent.com/assets/252023/6891870/47b7ba58-d6c7-11e4-834e-7b07a81d497b.png)
But it seems to be just the vim formatter malfunction. It renders fine on GitHub.
It doesn't break Sublime Text 2 or Mou either.
