### ISSUE TITLE
Coming up empty?

### ISSUE THREAD

**Issue by Naatan** [skywinder/github-changelog-generator#226]
I'm trying this out for Komodo/KomodoEdit, command output:

```
github_changelog_generator -u Komodo -p KomodoEdit -t REMOVED                                                                                                                                   [16:38:13]
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :exclude_labels=>["duplicate", "question", "invalid", "wontfix"],
 :pulls=>true,
 :issues=>true,
 :verbose=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :author=>true,
 :filter_issues_by_milestone=>true,
 :compare_link=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :branch=>"origin",
 :user=>"Komodo",
 :project=>"KomodoEdit",
 :token=>"REMOVED"}

Found 0 tags                   
Received issues: 92            
Fetching merged dates... Done!                     
Filtered pull requests: 11
Filtered issues: 81
Fetching events for issues and PR: Done!                    
Fetching closed dates for issues: Done!
Fetching tags: Done!             
Sorting tags..
Generating log..
Done!
Generated log placed in /home/nathan/Projects/komodo-changelog/CHANGELOG.md
```

CHANGELOG.md:

```
# Change Log



\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*
```

It's kind of weird that it says ` :branch=>"origin"`, rather than "master", but I could find no obvious way to change that..

**Comment by skywinder** [comment]
@Naatan Hi.
The problem, that you dan't have any tags in this repo.

    Found 0 tags

It seems, that you are using outdated version. In new version You will found Yellow warring message in the beginning:

> Warning: Can't find any tags in repo. Make sure, that you push tags to remote repo via 'git push --tags'

**Comment by Naatan** [comment]
I'll try updating, but is it required to have tags? Could this operate strictly on Milestones?

I don't want to generate a changelog on commits, just on issues / milestones.

**Comment by skywinder** [comment]
@Naatan 
>I'll try updating, but is it required to have tags?

Until now - yes.

>Could this operate strictly on Milestones?

It's not easy to implement, because Change log is time-based file. In my scenario milestones used only to fix issues, that closed not wrong time range.

Milestones don't have any bindings to the time by themself. So I don't know, how to compound change log only from milestones.
Also, not all milestones should be included to change log. So we have to add separate list distinguish them.

>I don't want to generate a changelog on commits, just on issues / milestones.

Only issues and pull requests. Commits are not supported yet anyway (#51 for details)

**Comment by skywinder** [comment]
BDW: about `branch` - you are right. Actually - it's means `remote`. I will fix this typo.

**Comment by osiloke** [comment]
Hi, i was about to ask this same question becuase i expected to get an unrealeased section similar to that what you have in this projects changelog. Does this only show up after the first tag because "Unrealeased" is not a tag in this repo but yet it shows up in the changelog.

**Comment by skywinder** [comment]
@osiloke You're right. It `Unreleased` start works if you have at least 1 tag in repo. 
But it's possible to modify this logic. I add new issue, related with this feature #228. 
Have a lot of work next month. But will be glad to accept PR with this feature. :wink:
