### ISSUE TITLE
Getting an error `parse_options': invalid option: --max-issues (OptionParser::InvalidOption)

### ISSUE THREAD

**Issue by deezahyn** [skywinder/github-changelog-generator#229]
```
ruby-2.1.1/gems/github_changelog_generator-1.3.11/lib/github_changelog_generator/parser.rb:108:in `parse_options': invalid option: --max-issues (OptionParser::InvalidOption)
```

seems like --max-issues option doesn't work.

**Comment by aaronmcadam** [comment]
There's not been a release since March 21, that's why

**Comment by skywinder** [comment]
@aaronmcadam you're absolutely right. It's time :watch: 

@deezahyn I will release new version in a seconds. Please, update gem few minutes later!  :wink:

**Comment by aaronmcadam** [comment]
Thanks @skywinder, hope this will allow me to use this gem with my longer-running projects!

**Comment by skywinder** [comment]
Please, welcome `1.4.0`!

**Comment by deezahyn** [comment]
welcome 1.4.0 !
