### ISSUE TITLE
GitHub token generation link in README should lead to `personal access token` page

### ISSUE THREAD

**Issue by JMLamodiere** [skywinder/github-changelog-generator#232]
In the [GitHub token](https://github.com/skywinder/github-changelog-generator#github-token) section of README.md, not sure why the link `you can easily generate it here` leads to [Applications](https://github.com/settings/applications) ? From this page, we can only register an Oauth application with a mandatory `Authorization callback URL`. It doesn't seem to make sense.

Shouldn't it lead to [Personnal access token](https://github.com/settings/tokens) instead ? It's the page I've used to create and successfully use a token with this changelog-generator.

If you agree with that, I can make the tiny PR required to change that.

**Comment by skywinder** [comment]
You're right! Thanks for mention!
