### ISSUE TITLE
github_changelog_generator.rb:220:in ``': No such file or directory - pwd (Errno::ENOENT)

### ISSUE THREAD

**Issue by vcaldas** [skywinder/github-changelog-generator#237]
Hi Skywinder,
Awesome job btw! I'm having this problem:
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator.rb:220:in ``': No such file or directory - pwd (Errno::ENOENT)
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator.rb:220:in `compound_changelog'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.4.0/bin/github_changelog_generator:4:in `<top (required)>'
        from c:/Ruby22-x64/bin/github_changelog_generator:23:in `load'
        from c:/Ruby22-x64/bin/github_changelog_generator:23:in `<main>'

The changelog looks ok, but I'm not sure if I'm missing something. Let me know how can I help.
Sorry if this is not the place for that.
btw. Running windows8
Thanks!

**Comment by skywinder** [comment]
@vcaldas Great! It's just a last string in the script where I use linux command `pwd`.
It doesn't affect to anything. And I will fix it in next release. Thank for mention it! :+1:

**Comment by vcaldas** [comment]
Great! Congrats again!

**Comment by skywinder** [comment]
@vcaldas don't have windows to test, but hope it fixed, please, check version `1.4.1`!

**Comment by vcaldas** [comment]
@skywinder I'll get the last version and give you feedback asap!

**Comment by vcaldas** [comment]
@skywinder Just tested an no error messages. Cheers!

**Comment by skywinder** [comment]
@vcaldas Hooray! :trophy:
