### ISSUE TITLE
Arbitrary templates

### ISSUE THREAD

**Issue by skywinder** [skywinder/github-changelog-generator#242]
As @sds  mention here: https://github.com/brigade/overcommit/pull/212#issuecomment-105063302
Eliminate putting redundant empty lines in change log.

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by skywinder** [comment]
@ErjanGavalji  I update a little bit this issue and separate it on small sub-tasks. Can you specify, which of these features is most wanted for you? I believe #241, right?

**Comment by zbeekman** [comment]
This would be nice. I think right now there is so much wasted space with the blank lines between each issue/PR/enhancement that it makes it hard to skim/read/digest the contents of the changelog.

**Comment by szaghi** [comment]
:+1:
