### ISSUE TITLE
Exclude and Include tags is broken

### ISSUE THREAD

**Issue by CharlesAHunt** [skywinder/github-changelog-generator#245]
There are a couple issues here. The first is that the --exclude-tags and --between-tags fail every time with "can't find tag x.x.x...". I have tried in various ways(i.e --exclude-tags=0.8.170, --exclude-tags 0.8.170, --exclude-tags="0.8.170", etc, and with various other tags that do exist both on local and remote).  The second issue, as seen below is that it's interpreting --exclude-tags as '--between-tags'

> github_changelog_generator -t {mytoken} --exclude-tags=0.8.170
Detected user:...
Performing task with options: ...
 :exclude_tags=>["0.8.170"],
 :user=>"researchnow",
 :project=>"nova-flare"}
Found 134 tags
Warning: can't find tag 0.8.170, specified with --between-tags option.

**Comment by skywinder** [comment]
Got it! Will fix it soon! Thanks! :+1:
