### ISSUE TITLE
--user and --project options are broken

### ISSUE THREAD

**Issue by dalen** [skywinder/github-changelog-generator#246]
It seems like the script expects a undocumented URL to the repo instead of the user specifying --user or --project options. Also looking at the code it seems like only specifying one of them would be broken.

It should do all the auto detection first and then overwrite that with whatever was specified on the command line.

**Comment by skywinder** [comment]
Thanks for mention it. I will take a look.

**Comment by skywinder** [comment]
Thanks! Will be fixed in `1.5.1` today.
