### ISSUE TITLE
Generate change log since/due specific tag

### ISSUE THREAD

**Issue by dguo** [skywinder/github-changelog-generator#254]
Hi, is there a way to generate the log since a particular tag? The `--between-tags` option doesn't seem to allow this. I tried doing a hack where I used git to get the latest tag and then pass it to the `github_changelog_generator` command, but the output is different from what I expected. The `--between-tags` option seems to roll up all the pull requests in between into the later tag, instead of listing each tag in between. I did not expect that, but I assume that is the intended behavior?

**Comment by skywinder** [comment]
Hi! I close #210 recently in favor of `--between-tags` option. But now I see, that such option could be useful in case like yours.

**Comment by skywinder** [comment]
there is need to implement `--due-tag` to complete this issue. In a similar manner as #257

**Comment by raphink** [comment]
`due_tag` should be able to be implemented in a very similar way to `since_tag`.

**Comment by skywinder** [comment]
Exactly. That's what I said in previous comment. I will handle it soon.

**Comment by richrd** [comment]
I just started using this, and I think its great! :beers: And sorry for being lazy, but I wan't to chip in and voice my great interest for this project!

Can we (after this is closed) generate 'delta' changelogs e.g. add new changes to an old change log?
I have been developing my project and have generated meaningless PRs etc for myself etc. I'd like to be able to ignore the old stuff and just add all the new changes to my changelog.

My request mainly is: the ability to prepend new changes from a new version to the old changelog to avoid having to curate out some unnecessary stuff from changelog? (sorry to request if its already implemented)

**Comment by skywinder** [comment]
@richrd Very glad to hear that words. 
About your deature-request: I believe @raphink is kindly implement thing, that you requested there: #258 isn't it?

**Comment by richrd** [comment]
@skywinder thanks for the info, good to hear it's comming. And thanks a lot @raphink for implementing it. It's just what I need :+1: :)
