### ISSUE TITLE
We should add a git-generate-changelog command.

### ISSUE THREAD

**Issue by Natim** [skywinder/github-changelog-generator#255]
If `github_changelog_generator` was named `git-generate-changelog` it would be possible to call:

```
git generate-changelog
```

**Comment by skywinder** [comment]
@Natim cool idea! Did you know, how to implement it? Should I create additional executable in bin folder for that feature?

**Comment by Natim** [comment]
We can either add a symbolic link for ``github_changelog_generator`` to ``git-generate-changelog`` or create another executable that does the same thing as ``github_changelog_generator`` but named ``git-generate-changelog``.

Note that if you want ``git generate-changelog --help`` to work you should also add a manpage for it but it is not mandatory because ``git generate-changelog -h`` will work.

**Comment by Natim** [comment]
We can also try to approach https://github.com/tj/git-extras

**Comment by skywinder** [comment]
@Natim I really like this feature, right now I'm working hard on other projects, so can't implement  and test it properly in near future, but I if you would like to contribute to this project - I will be glad to accept PR with this feature. :wink:

**Comment by skywinder** [comment]
Done, thanks to @dlanileonardo

**Comment by olleolleolle** [comment]
\o/

**Comment by olleolleolle** [comment]
Oh, we've had this since February, I'll close this. Enjoy!
