### ISSUE TITLE
Output should not include security information

### ISSUE THREAD

**Issue by ahousing** [skywinder/github-changelog-generator#270]
If you use the "-t" argument to pass a token, then the output will display that information.  
```
:token->"40chars"
```
However, since this is confidential information, it probably shouldn't be displayed.  The correct behavior is what happens if you set environment variable CHANGELOG_GITHUB_TOKEN.

I've confirmed the behavior with 1.8.1.

**Comment by skywinder** [comment]
@ahousing thanks! Fixed!
