### ISSUE TITLE
Possible to customize the format?

### ISSUE THREAD

**Issue by alanhartless** [skywinder/github-changelog-generator#273]
Hi!

Does this support custom formats/templates?

**Comment by skywinder** [comment]
Hello. Yes. What you want to customize? These options ca help you:

        -f, --date-format [FORMAT]       Date format. Default is %Y-%m-%d
        --bugs-label [LABEL]         Setup custom label for bug-fixes section. Default is "**Fixed bugs:**
        --enhancement-label [LABEL]  Setup custom label for enhancements section. Default is "**Implemented enhancements:**"
        --issues-label [LABEL]       Setup custom label for closed-issues section. Default is "**Closed issues:**"
        --header-label [LABEL]       Setup custom header label. Default is "# Change Log"

**Comment by skywinder** [comment]
@alanhartless Let me know if you need any help with formatting.

**Comment by alanhartless** [comment]
I was thinking more of the format.  For example, I prefer the PR#/link in front of each line rather the end.

**Comment by olleolleolle** [comment]
@alanhartless If you want to hack on the generation of markup, the file to begin with may be `generator_generation.rb`. You might come up with ideas for how you'd want to express the options you want to use. Or, you may just find a way to get your desired output.
