### ISSUE TITLE
Feature request: YAML front matter

### ISSUE THREAD

**Issue by retorquere** [skywinder/github-changelog-generator#276]
I use GCR to generate a changeling on my github-pages site; it would be nice if I could at the YAML front matter (or at least the title) to the generated file.

**Comment by raphink** [comment]
What do you mean by YAML front matter?

**Comment by retorquere** [comment]
The stuff that jekyll expects to set the title and such. It's just a block
of yaml text, but it'd allow generating the changelog straight to my github
pages site.

**Comment by gravitystorm** [comment]
Looks like this was added in https://github.com/skywinder/github-changelog-generator/commit/6f17e7c23633bebb56d4aab4976e34d4ade32d3c

**Comment by olleolleolle** [comment]
It sure does, @gravitystorm.

**Comment by retorquere** [comment]
By me in fact :)

**Comment by olleolleolle** [comment]
@retorquere Thanks for building it!
