### ISSUE TITLE
PRs not closed on master branch show up in changelog

### ISSUE THREAD

**Issue by asgeirbirkis** [skywinder/github-changelog-generator#280]
Sorry if this is a silly question that's been answered elsewhere (something similar seems to have been discussed in #37 and #60), or if I'm overlooking any option that takes care of this (I tried --since-tag, --no-unreleased and --filter-by-milestone) but I really like the output from the changelog generator and would love to use it for my project, and while I could manually edit the output now, that's an unattractive option in the long term.

Essentially, we're working with a GitHub Gitflow model, where we have a `development` branch for new features and major changes, and a `release` branch to be able roll out bug fixes. For example, we now released v5.2.1 from the release branch (merging it into master and adding a tag), while the next release from the development branch will be 5.3.

When I run the github_changelog_generator , it correctly detects that v5.2.1 is the latest release. However, it also lists issues and PRs that only got closed on the development branch since v5.2.0 as a part of the v5.2.1 release, even though those commits have not been released (i.e. they're only contained in the development branch, not the master branch). The Github release page correctly identifies that there have been 276 commits to development since release of 5.2.1, but that info does not seem to be carried over to the changelog generator.

Even issues and PRs that were assigned to a different milestone get included in the changelog generated.

Any help greatly appreciated, happy to send some output examples if needed. Would love to be able to add another entry to the list of projects that use the changelog generator!

**Comment by skywinder** [comment]
@asgeirbirkis Yes, I know about this behaviour. I think it's time to create separate issue for this.
It could be solved, if we find a way to check, is PR was merged to `master` or not. But I have no idea, how to check it with [GitHub API](https://developer.github.com/v3/)

**Comment by asgeirbirkis** [comment]
@skywinder Thanks for the quick reply. Afraid that I'm not an expert on the GitHub API, but would something like grabbing the sha of the last commit in the PR, and check whether it exists in the lists of commits on the branch work? The first tag that the PR's commit appears in would then be the version it belongs to.

Although as I said, not an expert on this, so not sure how feasible this plan is. Maybe somehow make further use of the milestones might be an option as well?

**Comment by SteveGilvarry** [comment]
Also seeing PR's merged on other branches as opposed to Master, looking at this https://developer.github.com/v3/pulls/#parameters seems like base would be the correct Parameter to use as a pull branch filter. Not to be confused with the --base option in generator.

**Comment by SteveGilvarry** [comment]
I tried this myself but not sure this is the best first time ruby project.
https://github.com/skywinder/github-changelog-generator/blob/master/lib/github_changelog_generator/fetcher.rb#L126
I believe this would work to only get the pull requests on branch master. Obviously turning it into an option would make the most sense.
`response = @github.pull_requests.list @options[:user], @options[:project], state: "closed", base: "master"`

**Comment by SteveGilvarry** [comment]
So now I have managed to get it to build and can tweak these values. But the next issue seems to be app pulls all issues and then filters that to a list of pull requests. Then it is only using pull_requests.list for merged dates, once it compares it's filtered list to the result of pull.requests.lists it hits null issues as I filtered the pull list by base: "master". So the two lists are not equal.
Any reason why it retrieves issues and pr's together, I am still digging, so someone may already know.

**Comment by skywinder** [comment]
@SteveGilvarry thanks a lot for your research! :+1: 

>Any reason why it retrieves issues and pr's together

Since PR's is subtype of issue - it retrieves them all together.

**Comment by SteveGilvarry** [comment]
@skywinder yes I got to that eventually including the notes all over the github api about issues and pull requests being a lot closer in the past. Surprised they haven't implemented a filter for issues and pr's on that.
Anyway I was thinking using the Pull Request API with a Base option to pass in the branch as a way to filter the pull request list. At the moment it assumes a match for everything in the list, so as soon as it fails start getting Nil errors.  I really have zero ruby skills so if that is something you have time for go ahead an swap it, if not I will play over the weekend and see if I can teach myself enough to fix it.

**Comment by skywinder** [comment]
@SteveGilvarry Cool! :+1:  Get in touch m8! Actually don't have a time to work on it. Hope I can back to project  1-2 weeks later,

**Comment by raphael-riel** [comment]
Look like @SteveGilvarry got up and running in Ruby and wrote the #305 PR to fix this!

**Comment by asgeirbirkis** [comment]
Great, looking forward to try this out!
