### ISSUE TITLE
Add a "documentation" label

### ISSUE THREAD

**Issue by lamont-granquist** [skywinder/github-changelog-generator#284]
This should probably get its own breakout category like "Enhancements" or "Bugs"

**Comment by skywinder** [comment]
@lamont-granquist now I'm use predefined labels only, that @Github uses in new projects by default.
I believe the closest label to `documentation` will be `wontfix`.
If you want to specify repo-specific labels - there is special options in the script.

**Comment by lamont-granquist** [comment]
Lol, okay that's how the labels already got into a project that I hadn't done any label-maintenance on...  I thought this gem was auto-adding them...

**Comment by lamont-granquist** [comment]
So can we customize the categories that render into the ChangeLog though?

**Comment by lamont-granquist** [comment]
Essentially, I'm looking for `--custom-section Documentation` or something like that, and then some way to add labels to the new section....

**Comment by olleolleolle** [comment]
Closing this in favour of the more general feature request #316. Thanks for filing the issue - you can subscribe to the other one to keep updated.
