### ISSUE TITLE
Several Issues with installing under Ubuntu 14.04

### ISSUE THREAD

**Issue by Voidi** [skywinder/github-changelog-generator#293]
I've encountered several problems trying to install this under Ubuntu:
1. Which ruby version?
I can install the packages ruby1.9.1 and ruby2.0, and maybe say which additional dependencys are needed see https://github.com/skywinder/github-changelog-generator/issues/64
2. The ruby script /usr/local/bin/github_changelog_generator has not execution right other then the owner, prevents from execution
3. running scripts abort with following error messages
`/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find github_changelog_generator (>= 0) amongst [rdoc-3.9.4] (Gem::LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
	from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
	from /usr/local/bin/github_changelog_generator:22:in `<main>'`
4. Point 4. seems related to that everything in `/var/lib/gems` has only read and execution rights for the owner. I don't know if this gem or the program ruby-gem or the linux package are responsible for this.

**Comment by wookiecooking** [comment]
Same issue

**Comment by skywinder** [comment]
@Voidi @wookiecooking Don't have ability to test it on Ubuntu. Please, let me know, if you find any solutions.

**Comment by Voidi** [comment]
After reinstalling this under Ubuntu 16.04. with the same Problems, it seems that the gem manager uses the umask of root, which i my case results in 700 file permissions.
So after all that seems not issue on our side.

**Comment by skywinder** [comment]
Thanks for update, @Voidi
