### ISSUE TITLE
since_tag seems to not be working

### ISSUE THREAD

**Issue by lamont-granquist** [skywinder/github-changelog-generator#304]
I'm running with this config:

``` ruby
GitHubChangelogGenerator::RakeTask.new :changelog do |config|
  config.since_tag = 'v5.0.0'
  config.exclude_labels = %w[duplicate question invalid wontfix changelog_skip]
  config.issues = false
end
```

And expecting that what I'll get is the contents of my HISTORY.md file, and only the PRs since v5.0.0 (grouped under 'unreleased').  What I'm getting is all the PRs in the project with no tag orgnization to them at all.  If I throw in `since_tag = 'v4.0.0'` then I do get a correct section for the unreleased tags, but then the v5.0.0 tag gets all the rest of the PRs.

I tracked it down far enough that it looks like `#delete_by_tag` is being passed 'nil' for both the older_tag and newer_tag which seems pretty clearly wrong, but hit a timebox and didn't track it down any further.

**Comment by lamont-granquist** [comment]
Link to PR with code + output of running 'rake changelog':

https://github.com/acrmp/foodcritic/pull/406

**Comment by grEvenX** [comment]
Having the same issue

**Comment by lamont-granquist** [comment]
So, and to be clear it looks like the `since_tag` works correctly for determining how many 'blocks' of PRs there are and their heading.  It also works for the top N-1 blocks/headings.  But the last block/heading gets all the rest of the PRs thrown in it and ignores the since_tag, effectively dumping all of the PRs into the changelog.

**Comment by swarzech** [comment]
+1

**Comment by lamont-granquist** [comment]
might be a dup of #282 ?

**Comment by sciutand** [comment]
:+1:

**Comment by skywinder** [comment]
@lamont-granquist  Hi. Is this issue still valid? Can you give me a name of your repo, if it's open sourced, in order to test it?

**Comment by lamont-granquist** [comment]
still valid last i checked.

acrmp/foodcritic was the repo i was testing it against, the PR linked to in the 2nd comment shows the results, you should be able to check out that PR against foodcritic and replicate the output.

**Comment by nrodriguez** [comment]
Still getting this issue with 1.14.3

**Comment by alexjfisher** [comment]
I can't get since_tag to work either.  I've been trying to migrate https://github.com/voxpupuli/puppet-archive

**Comment by alexjfisher** [comment]
@olleolleolle https://github.com/skywinder/github-changelog-generator/pull/438 doesn't seem to be working for everyone.  Do you have any idea what we might be doing wrong?

**Comment by alexjfisher** [comment]
I've figured out why it was working for me and opened a new issue https://github.com/skywinder/github-changelog-generator/issues/555
@nrodriguez Was your since_tag also the latest tag?
