### ISSUE TITLE
Separate by lists: Enhancements, Bugs, Pull requests.

### ISSUE THREAD

**Issue by skywinder** [skywinder/Github-Changelog-Generator#31]
Now it's used prefix for each issue, That look god in case 1-2 issues of the same type, but not very nice in case of 5+ same type issues.
It's needed to create at least 3 separate lists per version:
- Merged pull requests:
- Implemented enhancemets:
- Fixed bugs:

**Comment by williewheeler** [comment]
+1. Would look cleaner as headers rather than list item prefixes.

**Comment by skywinder** [comment]
@williewheeler Got it! I'm too! :) I will implement it on this week!

**Comment by runar** [comment]
I would like this feature as well. Has there been any progress? :)

**Comment by skywinder** [comment]
@runar Yep. It's one of the most important feature right now. But I have to fix some minor bugs before.
I'll try to find time for next week.

**Comment by skywinder** [comment]
@runar, @williewheeler, Hooray, guys, check it out! Version `1.3.0` already released! :tada:

**Comment by williewheeler** [comment]
Cool, will check it out shortly. Thanks Petr.

**Comment by williewheeler** [comment]
Looks great. Thanks!
https://github.com/ExpediaDotCom/seiso/blob/0.3.0/CHANGELOG.md
