### ISSUE TITLE
Ruby 2.3.0 - Deprecation warning: Github::ResponseWrapper#respond_to?(:to_ary) is old fashion which takes only one parameter

### ISSUE THREAD

**Issue by aaronmcadam** [skywinder/github-changelog-generator#323]
Hi, I'm seeing a lot of the following warnings when I run the gem:

```shell
/.../ruby/2.3.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/fetcher.rb:180: warning: Github::ResponseWrapper#respond_to?(:to_ary) is old fashion which takes only one parameter
/.../.gem/ruby/2.3.0/gems/github_api-0.13.1/lib/github_api/response_wrapper.rb:133: warning: respond_to? is defined here
```

**Comment by olleolleolle** [comment]
This is a message from [the github_api gem](https://github.com/peter-murach/github/issues)

Here is the implementation of `respond_to?`
https://github.com/peter-murach/github/blob/c7b4e08cf1f48d86ea071f545842246587d6a6e0/lib/github_api/response_wrapper.rb#L133

Here is a fix to it:

https://github.com/inukshuk/bibtex-ruby/commit/a65a370a8c7be93303c281477d1da65566cdad5f

**Comment by sparksp** [comment]
Looks like this has been fixed upstream now, you just need to `gem update github_api` on your local environment 😄
