### ISSUE TITLE
install error "Not a git repository"

### ISSUE THREAD

**Issue by sandrokeil** [skywinder/github-changelog-generator#339]
I've tried to install the `github-changelog-generator` 1.11.4 with different Ruby versions, but I get always this error:

```
ERROR:  Error installing github_changelog_generator:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -rubygems /var/lib/gems/2.2.0/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/github_changelog_generator-1.11.4 RUBYLIBDIR=/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/github_changelog_generator-1.11.4
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
LocalJumpError: unexpected return
/var/lib/gems/2.2.0/gems/github_changelog_generator-1.11.4/Rakefile:19:in `block in <top (required)>'
Tasks: TOP => default => copy_man_page_to_manpath
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.2.0/gems/github_changelog_generator-1.11.4 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/github_changelog_generator-1.11.4/gem_make.out
```
What are the requirements for this gem? I use [Docker](https://hub.docker.com/_/ruby/) for the different environments. An image with rvm also doesn't work.

Also tested with [Ruby 2.2 and Rubygems 2.4.8](https://github.com/skywinder/github-changelog-generator/issues/325), but same error.

Any ideas?

**Comment by olleolleolle** [comment]
Thanks for the report! I can tell what the defect is, because I caused it.

**Comment by olleolleolle** [comment]
See #341

**Comment by sandrokeil** [comment]
@olleolleolle Thank you for the fast reply. Good to know. ;-)

**Comment by olleolleolle** [comment]
Getting more convinced that I don't want an automatic install-that-man-page post-install step.

**Comment by jkeiser** [comment]
I have added a test for this in #344, that you might want to integrate into any fixes you do (to verify it doesn't regress again).

**Comment by olleolleolle** [comment]
This is fixed on master, will be in the next release.

**Comment by sandrokeil** [comment]
Thank you very much! :+1:

**Comment by skywinder** [comment]
Released v.1.11.5. 
Please feel free to reopen it, if you still have this issue.

**Comment by sandrokeil** [comment]
[It works](https://github.com/prooph/docker-files/tree/master/github-changelog-generator/master "Docker Image") like a charm. :+1:
