### ISSUE TITLE
changelog for private repos on an organisation

### ISSUE THREAD

**Issue by MehdiK** [skywinder/github-changelog-generator#342]
Hi, I have an organisation with a couple of private repositories. Is it possible to use github-changelog-generator to generate release-notes for these private repos?

Thanks.

**Comment by olleolleolle** [comment]
Yes! 

Generate a GitHub API token which has access to the repo you need to lookup metadata (PRs and such) for.

Then use this tool to make a changelog.

**Comment by olleolleolle** [comment]
@MehdiK Good luck!
