### ISSUE TITLE
Test installing on Windows: use AppVeyor

### ISSUE THREAD

**Issue by olleolleolle** [skywinder/github-changelog-generator#348]
We want to prove installing the gem on Windows is trouble-free using an AppVeyor GitHub build hook.

Can you build one? 

Please help!

**Comment by Arcanemagus** [comment]
Ruby is already installed for you in the AppVeyor containers at `C:\Ruby22-x64` (or [these other locations](https://www.appveyor.com/docs/installed-software#ruby) for different versions).

If I knew the build process for Ruby gems I could help further, but my experience is more configuring it to test linters...

**Comment by olleolleolle** [comment]
The script that tests installing a gem is the following:

```shell
gem build github_changelog_generator
gem install *.gem
```

You can see it in the `.travis.yml` configuration file.
