### ISSUE TITLE
Warn/fail when running on JRuby

### ISSUE THREAD

**Issue by perlun** [skywinder/github-changelog-generator#359]
It tends to take a long time with JRuby and not even be able to complete anyway:

```
Exception in thread "Thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

I think we should add something like `abort 'JRuby not supported' if RUBY_PLATFORM == 'java'` to the startup of `github_changelog_generator` to avoid this. A proper long-time fix would be to try and make it work with JRuby as well, but that's probably more work.

**Comment by olleolleolle** [comment]
Or, in the .gemspec? http://guides.rubygems.org/specification-reference/#platform=

**Comment by perlun** [comment]
Yes - good idea, even cleaner that way. But how will that work if you have a `Gemfile` for your project and want it to be usable in both `ruby` and `jruby` scenarios? Will you have to `platform:` that specific gem line then?

**Comment by olleolleolle** [comment]
The error to the user will be something like "Can't find a release matching your platform." from Rubygems/Bundler. Non-installable on those platforms.

**Comment by skywinder** [comment]
Since there is no any easy way to fix it - I will close it, since we are not going to support JRuby for now.
