### ISSUE TITLE
Wishlist: --exclude-tags could support a regexp/glob pattern

### ISSUE THREAD

**Issue by perlun** [skywinder/github-changelog-generator#362]
This is useful in our use case, when we tend to tag a version when it is being deployed to a particular environment. E.g.: version 1.2.3 deployed to the `tst` environment would be tagged as `tst_1.2.3`.

I can volunteer to fix this, if it is considered a useful feature. Suggestions on how it should work (new option or just change existing behavior of `--exclude-tags`?) are highly welcome.

**Comment by skywinder** [comment]
Implemented in 1.12.0 by #320

**Comment by perlun** [comment]
Excellent, thanks a lot!
