### ISSUE TITLE
Error installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by insuusvenerati** [skywinder/github-changelog-generator#364]
Getting an error when trying to install:

`Invalid gemspec in [/var/lib/gems/1.9.1/specifications/unicode-display_width-1.0.3.gemspec]: Illformed requirement ["< 3.0.0, >= 1.9.3"]
Invalid gemspec in [/var/lib/gems/1.9.1/specifications/unicode-display_width-1.0.3.gemspec]: Illformed requirement ["< 3.0.0, >= 1.9.3"]
Invalid gemspec in [/var/lib/gems/1.9.1/specifications/unicode-display_width-1.0.3.gemspec]: Illformed requirement ["< 3.0.0, >= 1.9.3"]
Invalid gemspec in [/var/lib/gems/1.9.1/specifications/unicode-display_width-1.0.3.gemspec]: Illformed requirement ["< 3.0.0, >= 1.9.3"]
Invalid gemspec in [/var/lib/gems/1.9.1/specifications/unicode-display_width-1.0.3.gemspec]: Illformed requirement ["< 3.0.0, >= 1.9.3"]
ERROR:  Error installing github_changelog_generator:
        rubocop requires unicode-display_width (>= 1.0.1, ~> 1.0)
`

Running ruby version: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Installed using sudo apt-get install ruby ruby-dev

**Comment by abreksa4** [comment]
+1

Same here on 14.04
