### ISSUE TITLE
Bugs, that closed simultaneously with push not appeared in correct version.

### ISSUE THREAD

**Issue by skywinder** [skywinder/Github-Changelog-Generator#37]
Example skywinder/ActionSheetPicker-3.0#111 and skywinder/ActionSheetPicker-3.0#112
should be in 1.3.9

**Comment by skywinder** [comment]
skywinder/ActionSheetPicker-3.0#111 should be in **1.3.12**

**Comment by skywinder** [comment]
Actually, it's not a bug:

This behaviour occurs, when you close issue by [commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) but NOT **`push` it to github before create a new version tag.**

In that case there `closed date` of the issue will be later than `date of tag`. That's why this issue goes to next tag.

**How to avoid it:**
- push your branches before create new version tag.

**How to fix, if you already create a tag and push it:**
- Use the `milestone` to explicit point to tag, when this bug was fixed. (e.g. if isuue shoud be in version `0.5.1` - set milesone for this issue `0.5.1`

**Comment by runar** [comment]
I’m having this issue as well, and hopefully your fix will work when released. Your milestone fix works for now, but I’d prefer to name my milestones different from my tags. Is there any way to test the development version?

I use the [GitFlow with GitHub workflow](http://datasift.github.io/gitflow/GitFlowForGitHub.html), and I think tags are created before the commits with issue references are pushed to master. The commits are pushed earlier, but to other branches than master, which means the referenced issues are not closed.

**Comment by skywinder** [comment]
@runar yes, I have exactly the same problem with GitFlow. 

**Actually, it's not a fix..** I notice, that GitHub close issues in range of 20-30 seconds after pushing. So, I just add a threshold in 60 secs for all issues (all issues, that closed in 1 minute after tag date also added to this release).

But I just understood that is works, because I do all my release versions with a script.
Thus, is's just workaround for my script, but not a fix. :(

**To detect related version properly:** We need to know, which commit cause closing event fot issue. (Then we can compare date of that commit, not the `closed_date`)

But don't know, how to get this information from github api.
Let me know, if you find solution.

**Comment by runar** [comment]
@skywinder: Thank you for your explanation!

I believe I have found something that hopefully may help. The following API call returns all events for an issue, including the «closed from commit» event:

```
GET /repos/:owner/:repo/issues/:issue_number/events
```

Here is the output of the call to an [issue closed from a commit](https://github.com/runar/gittest/issues/3) (with irrelevant data removed):

```json
[
  {
    "id": 235829856,
    "url": "https://api.github.com/repos/runar/gittest/issues/events/235829856",
    "actor": {
      "login": "runar",
      "id": 189879,
    },
    "event": "closed",
    "commit_id": "1f4150437672aff66cceeba8765c50f1caa2fc16",
    "created_at": "2015-02-14T11:02:24Z"
  }
]
```

On events closed the «normal» way (not from a commit), the `commit_id` is simply `null`.

The `"commit_id"` is the key here. This is the SHA hash of the commit from which the issue was closed. This SHA may be used to find out when the commit was created:

```
GET /repos/:owner/:repo/git/commits/:sha
```

Which will return (with irrelevant data removed):

```json
{
  "sha": "1f4150437672aff66cceeba8765c50f1caa2fc16",
  "url": "https://api.github.com/repos/runar/gittest/git/commits/1f4150437672aff66cceeba8765c50f1caa2fc16",
  "html_url": "https://github.com/runar/gittest/commit/1f4150437672aff66cceeba8765c50f1caa2fc16",
  "author": {
    "date": "2015-02-14T10:59:09Z"
  },
  "committer": {
    "date": "2015-02-14T10:59:09Z"
  }
}
```

I believe the `author.date` or `committer.date` is what you’re looking for.

I hope this helps!

**Comment by skywinder** [comment]
@runar  Awesome! Thanks! :ghost:

**Comment by runar** [comment]
@skywinder Let me know if you make it work and need help testing! :smile:

**Comment by skywinder** [comment]
@runar Done! It's time to check it! :) Version `1.2.8` in gem repo already!
