### ISSUE TITLE
To many Issues ?

### ISSUE THREAD

**Issue by TheFive** [skywinder/github-changelog-generator#389]
When I generate the Changelog i get the following error:
```
Warning: Can't finish operation: GitHub API rate limit exceeded, change log may be missing 
some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument.
```
If i reduce the number of issues, the changelog generator is finishing, but than the changelog itself is missing some (random) issues. (that can easily be seen in the diff).

Is there an other way to configure the changelog generator ?
(i am working with daily / weekly releases, so i have a huge amount of releases & issues).

My repository is:
https://github.com/TheFive/osmbc

**Comment by TheFive** [comment]
I have installed the newest version with gem install today.

**Comment by TheFive** [comment]
My actual idea is to put all release notes before 1.0.0 to history.md and generate only the later one, but i did not find a configuration for the changelog generator to manage that.

**Comment by skywinder** [comment]
I going to implement this logic in next releases.
Close in favor of #209.
