### ISSUE TITLE
Clone of GitHub Changelog Generator in Python

### ISSUE THREAD

**Issue by topic2k** [skywinder/github-changelog-generator#390]
Hello, i liked the output of GitHub Changelog Generator, but i wasn't able to get Ruby running (it). As i don't know Ruby but Python, i decided to try to port it.
The script ([pygcgen](https://github.com/topic2k/pygcgen)) is working and seems to do it's job right, but i wanna ask all of you, if you could try it and report any issues or do pull request. The options of the script only slightly differ from GitHub Changelog Generator.

For the future i hope i can adopt changes/fixes/new features from GitHub Changelog Generator to pygcgen.

**Comment by skywinder** [comment]
Thank you for warm words about this project. There's quite hard to port all the things to Python. Since this project is perfect work of several rubists for a year. To tell the truth, Python and Ruby is pretty similar by speed and functionality. So I don't think that there's any reason to port it to Python.

**Comment by topic2k** [comment]
Thanks for your answer.
Well, the reasons for me to port it were:
- i wasn't able to get ruby running the script,
- i don't know Ruby (but a good enough amount of Python),
- i was curios if i can get it ported.
Of course you are right, there is no real need or reason to port it. ;)  Anyway, it was fun and challenging learning a bit of Ruby that way.

BTW: Maybe you can add a label "question", "won't fix" or something else as i can't add a label.

**Comment by olleolleolle** [comment]
(Thanks, @topic2k!)
