### ISSUE TITLE
Changelog includes issues going back months too far

### ISSUE THREAD

**Issue by dylandhall** [skywinder/github-changelog-generator#394]
Changelog includes issues going back to feburary, when my last release (marked by --since-tag) is in June.

Maybe I'm using it incorrectly, or maybe I wasn't tagging correctly before.

My release is tagged on the master branch, perhaps it's using develop as a reference and missing the tag? Is there a way to do this by dates instead? Is this just an error?

**Comment by robbieaverill** [comment]
Same issue as #304

**Comment by olleolleolle** [comment]
Thanks for reporting and de-duplicating. Closing in favor of #304.
