### ISSUE TITLE
Contributors Section

### ISSUE THREAD

**Issue by muuki88** [skywinder/github-changelog-generator#398]
Hi,

Thanks for this nice helper tool. What I like to do for my project is to list all the contributors for a given release. Which could look like

```
**Contributors**

Thanks to all contributors that helped to create this release

- user1
- user2
- user3
```

**Comment by skywinder** [comment]
Hi, @muuki88!
I don't think, that is very common case for changelog generator. 
Feel free make a PR, or compound  it from the "Merged pull requests" section by regexp and shell script, if you want to. 😉

**Comment by muuki88** [comment]
@skywinder you are probably right. Thanks anyway :)
