### ISSUE TITLE
-bash: github_changelog_generator: command not found

### ISSUE THREAD

**Issue by aastudio** [skywinder/github-changelog-generator#403]
I did ```gem install github_changelog_generator```

My settings : 
- ```ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]```
- gem version ```2.4.5.1```
- ```Homebrew 0.9.9```

When I run ```github_changelog_generator```, I have the following message : ```-bash: github_changelog_generator: command not found```

**Comment by olleolleolle** [comment]
The command name uses dashes?

**Comment by aastudio** [comment]
I simply run ```github_changelog_generator```

**Comment by skywinder** [comment]
Could it related with `rvm` `chruby or `rbenv` settings? Is the other gem works in this way?

**Comment by olleolleolle** [comment]
Rbenv uses [a "rehash" command](https://github.com/rbenv/rbenv#rbenv-rehash) to build command-line wrappers around any executable that gems provide.

This issue has seen no response in a month. Re-open with more details, if it's still a problem.

Take care!

**Comment by pociej** [comment]
+1

**Comment by wanbinkimoon** [comment]
Same issue here on MAC OS Mojave 10.14

**Comment by bzon** [comment]
🤦‍♂

**Comment by bzon** [comment]
It would be nice if the installation can be managed with `brew` or as a single binary (rewritten in Go).

**Comment by skywinder** [comment]
@bzon sounds great! would be glad to merge this PR. 👍

p.s.

`github_changelog_generator: command not found`
somtime can be fixed by this:
https://superuser.com/a/1538816/230571

**Comment by TAGC** [comment]
Same issue. Been trying to get this working for over an hour now.

- Homebrew: 4.0.3
- macOS 12.6.1
- gem 3.4.6

**Comment by dingo-d** [comment]
Cannot get this working on Mac OS Ventura 13.2.1

- Homebrew 4.0.4
- gem 3.4.6

I'll try to see if Docker install will work.
