### ISSUE TITLE
Option to automatically add generated changelog to Github releases

### ISSUE THREAD

**Issue by aih** [skywinder/github-changelog-generator#462]
Does this option already exist? Does the github API allow it?

**Comment by olleolleolle** [comment]
Hello @aih! 

[Controlling Releases with the GitHub API](https://developer.github.com/v3/repos/releases/) is quite possible, but it feels like a tool to do that should be able to _consume an output_ from github-changelog-generator.

**Comment by aih** [comment]
That's a good idea-- I'll look into it. At first glance, it's not clear how
to add html to the commit body, but that's an issue to be resolved with the
Github API.
Thanks!
Ari

**Comment by skywinder** [comment]
@aih Hi! It's could be a great feature. I will close this in favor of #56. We can continue a discussion on that issue.
