### ISSUE TITLE
Auto Generate Next Semantic Version Number

### ISSUE THREAD

**Issue by Jonathonbyrd** [skywinder/github-changelog-generator#468]
It seems that this script would be able to know the last release tag number and know what enhancements, improvements, bug fixes were made in the unreleased version. **Would it be possible to have this script return the next semantic version for the unreleased version?**

I'm using this script as part of a Travis-CI process that will tag our software if the last tag is older than thirty days.

**Comment by skywinder** [comment]
@Jonathonbyrd Hi. it's not possible to predict, which semantic  (minor, major or patch) number will be updated. And it's not directly related to change log generation.

Nevertheless you can use `--unreleased-label` to specify manually next version.
