### ISSUE TITLE
Not Released

### ISSUE THREAD

**Issue by GeekOnCoffee** [skywinder/Github-Changelog-Generator#47]
Would love to add a flag that includes a Not Released section at the top which is all of the entries which haven't yet been tagged... not sure how easy/hard this would be, if you can give me some idea I can potentially look at implementing it.

**Comment by skywinder** [comment]
Actually it's should be so hard to implement. 
But What the purpose to highlight features, that not in release yet?
Can you provide more detailed example, how it should look?

**Comment by skywinder** [comment]
@GeekOnCoffee ok, I think I got your idea. 
You want to generate feature-list, that will be in next tag, isn't it?
What about to implement key for example `--next-release` which allow to generate list of features, that will be added to next tag only? It will fit your requirements?

**Comment by GeekOnCoffee** [comment]
Yup, that's exactly what I'm looking to do.

**Comment by skywinder** [comment]
@GeekOnCoffee Great! Good idea! :+1:  I will implement it soon!

**Comment by skywinder** [comment]
@GeekOnCoffee Done!
Usage:
- Now all unreleased issues on top of changelog. It's enabled by default ( use `--no-unreleased` to disable it ) 
- use `--unreleased-only` to generate list with unreleased issued only.

**Comment by skywinder** [comment]
@GeekOnCoffee  Hooray, check it out! Version `1.3.0` already released with this feature! :tada:

**Comment by GeekOnCoffee** [comment]
@skywinder awesome, thanks! I'd manually installed the gem from the github repo, but now I can update my instructions for the team.
