### ISSUE TITLE
Changelog generator does not work properly with forked repos

### ISSUE THREAD

**Issue by rnelson0** [skywinder/github-changelog-generator#472]
I am trying to create a changelog for https://github.com/voxpupuli/puppet-grafana. When I do, it is almost empty - just 1 merged pull request under version 2.6.0. It appears to be because the repo is a fork. When look at one of the Full Changelog links like https://github.com/voxpupuli/puppet-grafana/compare/v2.1.0...v2.5.0 I see that PR 59 and 61 were merged - but on the parent repo. You can see the generated changelog [here](https://p.bastelfreak.de/YyNqr/rmd).

Is there any way to take in this information from the parent repo automatically?

**Comment by rnelson0** [comment]
I'm pretty sure I know the answer but I have to ask and hope someone has a solution! Thanks for this tool, it's pretty awesome :)

**Comment by skywinder** [comment]
@rnelson0  This script work with you repo as the standalone project. Empty sections appeared because you don't have any closed issues or PR related to this tags.
I don't think, that it's necessary to support forked repo. If you forked it to make something new - you have to start your new change log. If you forked to implement and merge new feature - it will appeared in the main repo as soon as it will be merged there

**Comment by rnelson0** [comment]
@skywinder I understand why it's not working. Is it possible that it could be made to work? I am not that familiar with the GitHub API to know if it *can* pull from the upstream. If you think it can be done, though, and can provide a hint of where to start, I would be willing to try to create a PR for a feature flag.

Our use case is when a project is permanently forked from the original, rather than migrated, we want to preserve the history, and the changelog is not already in this style. Once it is, we could append it via `HISTORY.md` and bound the config to never go past some specific older version, but getting there is difficult.

Now that I've described it, I see that we could run this gem against the original fork between start and the last common version, but that's a manual effort and automating it would be nice, too. I'll have to think on that; at the least I could make a wiki article to describe that effort.

**Comment by skywinder** [comment]
@rnelson0 Thanks, I got the point. It could be done as soon as https://github.com/skywinder/github-changelog-generator/issues/252 will be implemented or this one: https://github.com/skywinder/github-changelog-generator/issues/213
Both of them will solve your issue. So I will close it in favor of most general task, that already created.

**Comment by rnelson0** [comment]
@skywinder Awesome, thanks. We'll see what we come up with and contribute a document and/or PRs as appropriate.

Again, thanks for this awesome tool!
