### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by drafie** [skywinder/github-changelog-generator#484]
I am getting this error when running it on a private repo. 

github_changelog_generator --token XXXXXXXXXXXXXX

/var/lib/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/xxxxx/xxxxxxx/tags?per_page=100: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)

 from /var/lib/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
        from /var/lib/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
        from /var/lib/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
        from /var/lib/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
        from /var/lib/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
        from /var/lib/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
        from /var/lib/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
        from /var/lib/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /var/lib/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
        from /var/lib/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
        from /var/lib/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
        from /var/lib/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
        from /var/lib/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:84:in `paginate'
        from /var/lib/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/client/repositories.rb:465:in `tags'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:77:in `block in calculate_pages'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:296:in `block in check_github_response'
        from /var/lib/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
        from /var/lib/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
        from /var/lib/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:295:in `check_github_response'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:76:in `calculate_pages'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:95:in `github_fetch_tags'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:68:in `block in get_all_tags'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:296:in `block in check_github_response'
        from /var/lib/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
        from /var/lib/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
        from /var/lib/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:295:in `check_github_response'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:68:in `get_all_tags'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator_tags.rb:9:in `fetch_and_filter_tags'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator_generation.rb:8:in `compound_changelog'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:34:in `run'
        from /var/lib/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        from /usr/local/bin/github_changelog_generator:23:in `load'
        from /usr/local/bin/github_changelog_generator:23:in `<main>'

**Comment by olleolleolle** [comment]
Wild guess: If you try using the ENV variable variant of the `--token`, does it do it differently?

**Comment by drafie** [comment]
No, same result.

**Comment by drafie** [comment]
End user error.   The GitHub token I created did not have sufficient privileges.   It requires the entire repo scope.

**Comment by olleolleolle** [comment]
To not waste your experience, can you author an error message to present together with 404 errors?

To get you started composing: 

- the user can check on the Web page if the project $PROJECT for the user $USER exists 
- the user can check if the token used for any Private project has the "Repos" privilege checked
