### ISSUE TITLE
Please document front-matter and release-url

### ISSUE THREAD

**Issue by 5chdn** [skywinder/github-changelog-generator#492]
Hi, I don't seem to understand the following options:

        --front-matter [JSON]        Add YAML front matter. Formatted as JSON because it's easier to add on the command line

What exactly does that allow me to do? Would be nice to have an example.

        --release-url [URL]          The URL to point to for release links, in printf format (with the tag as variable).

I tried to use `https://github.com/user/project/releases/%s` but it seems not to do anything, what is it supposed to do?

**Comment by olleolleolle** [comment]
front-matter creates ["YAML front matter"](https://jekyllrb.com/docs/frontmatter/)

**Comment by olleolleolle** [comment]
I searched the code here for `release-url` and this is the PR that introduced it:

https://github.com/skywinder/github-changelog-generator/pull/259

Hope this helps.

You're welcome to write documentation strings.

Perhaps as a part of the man page? https://github.com/skywinder/github-changelog-generator/blob/master/man/git-generate-changelog.md

**Comment by Lucashuang0802** [comment]
@olleolleolle looks like `release-url` is included already. 😃

**Comment by skywinder** [comment]
Cool, @Lucashuang0802 
Feel free to reopen the issue, if you still need help. 👍
