### ISSUE TITLE
What Tags to use to create Headings in Changelog

### ISSUE THREAD

**Issue by hendrikeng** [skywinder/github-changelog-generator#495]
Hey there, thanks for the awesome generator, it all works i just couldn't figure out wich tags to use in commit messages to create the headings like : 

```
Added feature:
.
.
.
Fixed bugs:
.
.
.
Implemented enhancements:
.
.
.
```

only closed issues was automatically generated in the changelog, i tried add: , fixes: etc...what am i missing..thanks a lot

**Comment by olleolleolle** [comment]
Labels, @hendrikeng. GitHub Labels. I'll add one now, to this GitHub Issue.

**Comment by hendrikeng** [comment]
@olleolleolle ah ok...i guess i misunderstood the whole concept then, so if i, in example, start a new project, i would create all features and functions i want to program as issues before i start, e.g. button xyz, when its finished, commit it with **feature #1 button** and  it would be stated in my changelog as feature implemented etc ....does that makes sense ? thanks a lot for your explanation

**Comment by olleolleolle** [comment]
Dark secret: each GitHub Pull Request _is_ an Issue (just with some more metadata on it, and displayed differently on the github.com website). Pull Requests are also sorted in under their (label) heading.

**Comment by hendrikeng** [comment]
Thanks a lot @olleolleolle :-)

**Comment by olleolleolle** [comment]
Have a great weekend.
