### ISSUE TITLE
Changelog Generator Requirements

### ISSUE THREAD

**Issue by gustavjf** [skywinder/github-changelog-generator#502]
In the Readme, you mention `"Here is a wikipage list of alternatives that I found. But none satisfied my requirements."`

Would you be able to share specifically what your requirements were?

**Comment by olleolleolle** [comment]
@skywinder That's a tricky one, for _you_. _Hugs!_

**Comment by gustavjf** [comment]
Just to add a bit, I noticed some of the links [here](https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives) only have an `"example"` link without cons. Some of those links are currently broken, but I was just curious why they're on the list if no particular cons were listed. 

Was it just to share other potential alternatives?

**Comment by olleolleolle** [comment]
`conventional-changelog` kindly adds a note about differences: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli#problems-with-github-changelog-generator-or-similar-projects 

It seems like an excellent project.

The list of missing features from this project is fair, and it reads like a TODO list.

**Comment by olleolleolle** [comment]
I hope this answers your enquiry.

**Comment by gustavjf** [comment]
Yes, thank you @olleolleolle!
