### ISSUE TITLE
Error On Running Generation Command

### ISSUE THREAD

**Issue by CDAGaming** [skywinder/github-changelog-generator#511]
Sorry in Advance if this is Easily Fixable, as im very new to using this 👍 
![2017-05-22](https://cloud.githubusercontent.com/assets/16328918/26307600/1187a4e4-3ebb-11e7-9214-b6c1d894a1f1.png)

**Comment by olleolleolle** [comment]
Hi, this has been fixed in master, and will be in the next release, thanks for reporting!

**Comment by CDAGaming** [comment]
I'll be looking forward to it, thanks for the assistance!

**Comment by CDAGaming** [comment]
Hey @olleolleolle Can I ask how I can build and utilize this from source so I'm able to generate still while awaiting next release

**Comment by olleolleolle** [comment]
@CDAGaming Perhaps you can be inspired about `specific_install`, a gem which offers a `gem` command to install from Git source? I blogged about it a bit: http://ollehost.dk/blog/2017/02/19/how-to-use-very-latest-bundler-in-travis/

**Comment by CDAGaming** [comment]
![2017-05-22 1](https://cloud.githubusercontent.com/assets/16328918/26309606/3874d588-3ec3-11e7-8d65-6e56ac4d513d.png)
Well, Specific Install Worked and it got a bit further, now its this error @olleolleolle 
Once Again, thank you for your time so far to assist, i really appreciate it 👍

**Comment by olleolleolle** [comment]
@CDAGaming See https://github.com/skywinder/github-changelog-generator/pull/480 on why Windows has this problem.

**Comment by CDAGaming** [comment]
Ah, WIP I see. Then I'll go with the next thing which is downgrading to a working version(Most likely v1.13.2), thanks for the help on this and hope that issue can be resolved sometime soon :+1:
