### ISSUE TITLE
Output in reStructuredText format

### ISSUE THREAD

**Issue by Pawamoy** [skywinder/github-changelog-generator#528]
Most Python projects use RST format for their documents, including CHANGELOG.rst. It would be great if outputing in RST was possible, instead of Markdown :airplane:

**Comment by Pawamoy** [comment]
Asking question and searching for answers just after is what I do. I realised that you can use Pandoc to convert from markdown to rst very  easily:

```bash
github_changelog_generator
pandoc -o CHANGELOG.rst CHANGELOG.md
rm CHANGELOG.md
```

**Comment by skywinder** [comment]
Thank you very much for update. Since this task could be easily fixed - I will close it. Cheers!
