### ISSUE TITLE
[question] May I select pull-req to add changes to CHANGELOG.md?

### ISSUE THREAD

**Issue by sachin21** [skywinder/github-changelog-generator#529]
May I I select pull-req to add changes to CHANGELOG.md?
I don’t want to include pull-req's changes to CHANGELOG.md at sometimes.

This question from this tweet https://twitter.com/SkyWinder/status/877545052398071808 .

```
to: @SkyWinder
Hi! May I select pull-req to add changes to CHANGELOG that pickup PR? I don’t want to include PR’s changes to CHANGELOG at sometime. 
```
```
to: @sachin21__
Yes, you can! Send this question to the repo please for detailed answer. ;) 
```

Question should post to stackoverflow..etc but I make this issue by kindness of @skywinder .

**Comment by olleolleolle** [comment]
There are tricks! 

- tagging issues using Labels allows you to exclude them

**Comment by sachin21** [comment]
@olleolleolle Thanks! But I haven't the permission to add the label. If you don't mind, could you add some label?

**Comment by skywinder** [comment]
You have to ask the owner of the repo to add this label or add you as
collaborator to do that. Cheers.
