### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Furtif** [skywinder/github-changelog-generator#536]
Filtered issues: 13
C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/github-changelog-generator-fb7e21f9f89f/lib/github_changelog_generator/generator/generator_generation.rb:25:in `include?': no implicit conversion of false into String (TypeError)
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/github-changelog-generator-fb7e21f9f89f/lib/github_changelog_generator/generator/generator_generation.rb:25:in `compound_changelog'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/github-changelog-generator-fb7e21f9f89f/lib/github_changelog_generator.rb:35:in `run'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/github-changelog-generator-fb7e21f9f89f/bin/github_changelog_generator:5:in `<top (required)>'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bin/github_changelog_generator:23:in `load'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bin/github_changelog_generator:23:in `<main>'
Fetching events for issues and PR: 93
Fetching closed dates for issues: Done!
Generating log...
Command exited with code 1

**Comment by olleolleolle** [comment]
@Furtif thanks for reporting this! 

@Lucashuang0802 Perhaps you have a follow-up to to #507 - something like `unless log.include?(credit_line)`?

**Comment by Furtif** [comment]
@olleolleolle ok https://github.com/Furtif/github-changelog-generator is update an error almost

**Comment by Lucashuang0802** [comment]
@olleolleolle would that change you proposed made a difference? Logically, it seems like the same thing.

**Comment by Lucashuang0802** [comment]
@olleolleolle sorry, I just read the error. 😃  Let me try that. What's your suggestion to test the Windows machine?

**Comment by Furtif** [comment]
appveyor

**Comment by Lucashuang0802** [comment]
@Furtif we have merged a change. can you confirm if it fixes your issue? thanks. 😄

**Comment by Furtif** [comment]
How to confirm? The issue has opened !!! The test is there the error in question

**Comment by Lord-Haji** [comment]
@Furtif close this, this is fixed

**Comment by olleolleolle** [comment]
Fixed in #537. 

Thanks for reporting!

**Comment by Lucashuang0802** [comment]
thanks @Lord-Haji

**Comment by Furtif** [comment]
👍

**Comment by Furtif** [comment]
thanks :)
