### ISSUE TITLE
Credit line bug

### ISSUE THREAD

**Issue by Lord-Haji** [skywinder/github-changelog-generator#541]
https://github.com/Necrobot-Private/NecroBot/commit/4ba9964d4008a63dad2290fd06c5cac760d54fd5#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
```diff
-\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*
+#{credit_line}
```

**Comment by Lucashuang0802** [comment]
@Lord-Haji @olleolleolle sorry for this buggy change. I will take a look. 😄

**Comment by Lucashuang0802** [comment]
@Lord-Haji thanks for reporting. The change is in.

**Comment by Lord-Haji** [comment]
@Lucashuang0802 Thanks!
