### ISSUE TITLE
Remove the URL in the repository's description section

### ISSUE THREAD

**Issue by olleolleolle** [skywinder/github-changelog-generator#545]
The link `https://skywinder.github.io/github-changelog-generator/` has outdated information.

That link is presented in the first part of the description, and new users will use it to learn.

And there will be slightly outdated things.

Proposed solution: Remove that link.

**Comment by olleolleolle** [comment]
@skywinder Could you remove that link in the project's metadata in the description part of the page?

**Comment by skywinder** [comment]
Oops. Just found it. Fixed. 😸

**Comment by olleolleolle** [comment]
<3
