### ISSUE TITLE
question: how to append changelog with only current version changes.

### ISSUE THREAD

**Issue by riuvshin** [skywinder/github-changelog-generator#547]
hi there I have repo with huge amount of PRs and Issues and Im looking for a way how to not regenerate whole change log for all versions each time. I need only append existing changelog with changes for concrete version is that possible?

another question - how to filter merged PRs by labels? I want to sort PRs like 
**BUG merged PRs:**
- 1 
- 2

**Enhancement merged PRs:**
- 1
- 2

**Comment by olleolleolle** [comment]
I don't believe that the first thing is possible - there is no "early return" from the fetching and processing of GitHub metadata. 

The second scenario: well, the Merged PR section "is for" showing unlabeled things. By adding Labels, you can get them out of that list of unlabeled PRs. The default list of labels recognized is extensible and configurable. See --help or man pages. 

Hope this helps!

**Comment by riuvshin** [comment]
thanks for the reply @olleolleolle , I;ve found that I could use `--since-tag  x` to workaround 1) but it still not clear how to append changelog... if that is not possible I will generate it in separate file and then will merge it but this is not something I wanted :)
2) yes i've tried `--bug-labels` and `--enhancement-labels` but this works only for issues not for PRs.
