### ISSUE TITLE
Support all Types of changes listed in Keepachangelog 1.0.0

### ISSUE THREAD

**Issue by olleolleolle** [skywinder/github-changelog-generator#558]
[Keep a Changelog 1.0.0](http://keepachangelog.com/en/1.0.0/) lists these Types of changes:

> ### Types of changes
> 
> `Added` for new features.
> `Changed` for changes in existing functionality.
> `Deprecated` for soon-to-be removed features.
> `Removed` for now removed features.
> `Fixed` for any bug fixes.
> `Security` in case of vulnerabilities.

Should the tool support all of these?

**Comment by abdonrd** [comment]
Any news about that? Thanks in advance!

**Comment by olleolleolle** [comment]
@abdonrd Pull Request and code ideas are welcome.

**Comment by olleolleolle** [comment]
Closed in #636! Thanks!
