### ISSUE TITLE
Options to show commit messages?

### ISSUE THREAD

**Issue by ksrb** [skywinder/github-changelog-generator#581]
Is there a way to just include the entire set of commit messages for now?
I've been staring at the documentation and trying various options but haven't managed to figure it out if exists.

Something like:
```
github_changelog_generator --include-commit-messages
```

**Comment by olleolleolle** [comment]
@ksrb I guess there isn't.

There are several other changelog generators out there that take this route. Or use `git log` in some permutation?

**Comment by ksrb** [comment]
Yeah I've been looking at some of the alternative in this repo's https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives. 

But google and github are telling me that this project is by far the most active 😉 .

What's going on with this project though, is it mostly just in maintenance now? No new features?

**Comment by olleolleolle** [comment]
@ksrb You're talking to the active community right now.

**Comment by ksrb** [comment]
Understood no worries thanks for responding.

**Comment by skywinder** [comment]
Close it in favor of #51 
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure, @ksrb  👍

**Comment by ksrb** [comment]
It would be cool to see it added but unfortunately I'm not using this project right now so I wouldn't be able to test it 😞 .
