### ISSUE TITLE
issue_line_labels and breaking_labels fail as rake file config params

### ISSUE THREAD

**Issue by richnsoos** [skywinder/github-changelog-generator#583]
As suggested in [the documentation](https://github.com/skywinder/github-changelog-generator#rake-task) I have a rake task to which I'm passing config parameters; however, issue_line_labels and breaking_labels trigger the following failures:

```
NoMethodError: undefined method `issue_line_labels=' for #<GitHubChangelogGenerator::RakeTask:0x00007f90c210f3d8>
```

```
NoMethodError: undefined method `breaking_labels=' for #<GitHubChangelogGenerator::RakeTask:0x00007fdee117b250>
```

This is how I'm setting the config params:
```
  config.include_labels = []
  config.exclude_labels = []
  config.bug_labels = []
  config.enhancement_labels = []
  config.breaking_labels = []
  config.issue_line_labels = []
  config.exclude_tags = []
```

All others config params are processes without error.

Any advice?

**Comment by olleolleolle** [comment]
Cool, you found a defect!

**Comment by richnsoos** [comment]
cool! @olleolleolle  has the gem been released yet?

**Comment by olleolleolle** [comment]
@richnsoos I will be making a new pre-release, which can be tried using `gem install github_changelog_generator --pre`

**Comment by richnsoos** [comment]
cc: @pantocrator27

**Comment by olleolleolle** [comment]
@richnsoos A new --pre was just released.

**Comment by richnsoos** [comment]
i validated that version [1.15.0.pre.rc](https://rubygems.org/gems/github_changelog_generator/versions/1.15.0.pre.rc) of changeloggenerator does handle issue_line_labels successfully. thank you!

**Comment by skywinder** [comment]
🎉  Olle, you're awesome!
