### ISSUE TITLE
Use it with GitLab

### ISSUE THREAD

**Issue by denis-peshkov** [skywinder/github-changelog-generator#590]
is it possible to use it with GitLab?
if yes, pls help me how to do it... 

I installed it from npm 
`npm install -g github-changelog-generator`
then, can't understood how to run it using **gh-change-gen**

**Comment by olleolleolle** [comment]
@denis-peshkov This is another project. That project is Node.js, this one is Ruby.

And, no, no GitLab support.

**Comment by olleolleolle** [comment]
Hope this helps!

**Comment by vitalkanev** [comment]
I will add this generator to the Alternatives wiki page. :+1:
