### ISSUE TITLE
Dockerfile and Docker automated builds

### ISSUE THREAD

**Issue by ferrarimarco** [skywinder/github-changelog-generator#591]
Hi @olleolleolle 

Would you mind accepting a pull request for a Dockerfile? I can also configure a Docker Hub automated build that runs on each tag (even on each commit if that is the desired behaviour).

**Comment by olleolleolle** [comment]
I’d be happy to have a PR!

**Comment by ferrarimarco** [comment]
Ok, I'm working on it.

How do you publish new releases on Rubygems? I need this info to think about the Dockerfile and the configuration of automated builds

**Comment by ferrarimarco** [comment]
@olleolleolle here it is: #592

**Comment by olleolleolle** [comment]
@ferrarimarco I use the `rake release` Rake task to make new versions?

**Comment by ferrarimarco** [comment]
As soon as (and if) #592 is merged I'll configure the Docker Hub automated build if it's fine for you

**Comment by ferrarimarco** [comment]
Ok I can now configure the Docker automated build. Which prefix should we use for the image?

**Comment by ferrarimarco** [comment]
@olleolleolle I don't have access to this repo configuration, so I cannot enable the automatic build all by myself.

Let's explore the options:

### Automated build with Docker hub

If we want to use (like previously suggested) Docker Hub for builds we should (since skywinder is a user account on GitHub and not GitHub Organization):
1. Register a new account on Docker Hub (let's call it docker-hub-user in this example)
1. Link docker-hub-user with github.com/skywinder (anyone doing this must know github.com/skywinder credentials)
1. Let me add docker-hub-user in the skywinder Docker Hub organization (I created it moments ago)
1. Use docker-hub-user to create a new automated build from GitHub and choose "skywinder" as namespace when creating it. Since docker-hub-user has been linked to github.com/skywinder, it will have access to this repo
1. Let me configure the automated build for you (since I'm a member of the skywinder organization I have the rights to do so)

### Automated build with Travis CI

Each time a tag is pushed, we use Travis CI to build the Docker image and push it under the skywinder Docker Hub organization. For this we need update the `.travis.yml` (I can do that) but you (or someone who has the proper rights) should update the Travis build configuration because we need to set the Docker Hub credentials in Travis CI.

This approach has the added benefit that we can use Travis CI environment variables (in our case we are going to use the git tag) to tag the docker image and to pass it as a build time variable instead of hardcoding the version in the Dockerfile.

Note 1: we should run the "build docker image & push to docker-hub" step as the very last, after the gem has been uploaded on Rubygems. So this approach is not suitable if you want to deploy on Rubygems in another context (i.e. not from Travis CI).

Note 2: as said, we should run the "build docker image & push to docker-hub" step only on when a new tag is published on GitHub because the Dockerfile I provided downloads GitHub Changelog Generator from Rubygems and does not compile it from source. It's possible to implement a Dockerfile for this use case (that will work on each commit, pull request and tag), but this is another story (I can help you in this also if needed).

**Comment by olleolleolle** [comment]
Skywinder is the GitHub username of a _person_. (Hi, @skywinder!)

Perhaps the time has arrived when we must use an org?

**Comment by ferrarimarco** [comment]
I know he's person :)

I created a skywinder organization on Docker Hub so everyone in that org could manage its Docker images. Otherwise we would have to share the credentials.

And yes, by creating a GitHub organization we could solve this issue.

**Comment by skywinder** [comment]
Hello everyone!
Make sense. Any ideas about naming? 
The Same name such as github-changelog-generator?
So it seems we have to create a logo for such a big deal 😉

**Comment by ferrarimarco** [comment]
the same name seems resonable to me :+1:

**Comment by riuvshin** [comment]
still no automated build for github-changelog-generator ? 

`docker run -it --rm -v "$(pwd)":/usr/local/src/your-app skywinder/github-changelog-generator` fails beacuse there is no such image :)

**Comment by ojongerius** [comment]
Hey there! Any luck with this work? There is an image, https://hub.docker.com/r/skywinder exists. Just a matter of adding this repository, no?

**Comment by olleolleolle** [comment]
@ojongerius Would you care to put those words into a PR to the README?

**Comment by ferrarimarco** [comment]
@ojongerius https://hub.docker.com/r/skywinder was created before #595 
It will be deleted in the coming days (otherwise @skywinder would have his username already taken on Docker Hub).

**Comment by ferrarimarco** [comment]
@olleolleolle @skywinder if we want to move ahead before #595, we have some alternatives (but let's wait for the deletion of skywinder organization I asked today):
1. @skywinder could register an account on Docker Hub, create a github-changelog-generator repository and grant me access to it as a collaborator to that repo and to the Travis build so I can set things up
1. I could setup a Docker Hub repository (ferrarimarco/github-changelog-generator) in sync with this repo and then when #595 is completed we can create the corresponding organization on Docker Hub and move ferrarimarco/github-changelog-generator to that organization

**Comment by olleolleolle** [comment]
@ferrarimarco Do you want to shepherd the Docker parts? Welcome! Awesome. 2 is a good option, then!

**Comment by ferrarimarco** [comment]
@ojongerius @riuvshin you can use https://hub.docker.com/r/ferrarimarco/github-changelog-generator/

**Comment by ojongerius** [comment]
@ferrarimarco could you please update the README to use that url instead of the current broken link?

**Comment by ferrarimarco** [comment]
there is a PR for that #634
