### ISSUE TITLE
Docker image missing?

### ISSUE THREAD

**Issue by adrian1358** [skywinder/github-changelog-generator#594]
Hi,

tried to install this tool a few days ago, and today I tried again and still the same issue.

So after entering the command from the docs:

`docker run -it --rm -v "$(pwd)":/usr/local/src/your-app skywinder/github-changelog-generator`

I receive:

`Unable to find image 'skywinder/github-changelog-generator:latest' locally
docker: Error response from daemon: pull access denied for skywinder/github-changelog-generator, repository does not exist or may require 'docker login'.`

Can you check please?

Thanks!

**Comment by vitalkanev** [comment]
Docker image is still work-in-progress. Visit https://github.com/skywinder/github-changelog-generator/issues/591 for more information

**Comment by olleolleolle** [comment]
Closing in favor of #591
