### ISSUE TITLE
Readme: Do I need to run commands as user or root?

### ISSUE THREAD

**Issue by mueller-ma** [skywinder/github-changelog-generator#598]
Hey,
I'm unfamiliar with gem and docker, so it would be nice to add `$` or `#` (or `sudo`) in front of all commands, so everyone knows if they need to be run as normal user or as root.

**Comment by olleolleolle** [comment]
Run them as normal user. 

Could you make a PR with this improvement?

**Comment by mueller-ma** [comment]
Also the gem command?

**Comment by olleolleolle** [comment]
Fixed in #602 - thanks!
