### ISSUE TITLE
Generator doesn't work when I run the command presented in the docs

### ISSUE THREAD

**Issue by agisilaos** [skywinder/github-changelog-generator#599]
Hey everyone, I'm trying to run the generator so I can create a changelog file but when I run the command github_changelog_generator - u user -p project I get this weird error message. Any ideas why this might happen? 🤔 

<img width="1368" alt="screen shot 2017-12-12 at 16 17 22" src="https://user-images.githubusercontent.com/10944108/33889318-61f38ebe-df58-11e7-8968-a1f29048f4c4.png">

<img width="1368" alt="screen shot 2017-12-12 at 16 17 29" src="https://user-images.githubusercontent.com/10944108/33889319-621774dc-df58-11e7-8676-465d0490b332.png">

cc: @skywinder

**Comment by olleolleolle** [comment]
Short answer: the README describes the upcoming version. 1.14.x had a different behavior. 

For 1.14.x:

To generate a changelog for Project foo by user sven: instead of “-p foo -u sven” write “sven/foo”.

**Comment by agisilaos** [comment]
Wow, I'm not so sure how I missed that because I read the docs, thanks for answering so quickly @olleolleolle and sorry for opening such a "lame" issue. 😢  Issue has been sorted out 👍

**Comment by olleolleolle** [comment]
@agisilaos Thanks for asking, and don't be sorry. Your screenshots were clear, you did all you could. The next person will be able to find this conversation and learn. You left this thing better than you found it.
