### ISSUE TITLE
Pull Requests in Wrong Tag

### ISSUE THREAD

**Issue by GeekOnCoffee** [skywinder/Github-Changelog-Generator#60]
We're using a workflow similar to Gitflow (http://nvie.com/img/git-model@2x.png) which means we've got pull requests that get merged into develop, but sometimes hot fixes get merged into release and put in a tag without merging develop, but currently all the Pull requests that have been merged into develop show up in that version. 

Is there any solution for this, or we going to be out of luck?

**Comment by skywinder** [comment]
I'm not completely understand difference between your and git flow workflow.
Can you provide example of your case?

**Comment by GeekOnCoffee** [comment]
I think our workflow matches gitflow, we're just not using the automated tool for doing it.

**Comment by skywinder** [comment]
@GeekOnCoffee yes, it's my own generated script for bumping: [bumper_pusher](https://github.com/skywinder/bumper_pusher) :) 

However, I didn't occur such problems in my repo, but I just created special test repo, and here is a bug! The simple hotfix and now PR in Unreleased section! Thanks for pointing on that! I will handle it soon. Hope this fix will resolve your case too!

**Comment by skywinder** [comment]
I believe it's the same problem as #37! So, I have to implement additional checks, and compare not a `merged_date`, but date of commit, that merge this PR!

**Comment by skywinder** [comment]
@GeekOnCoffee Done! :tada: Try a new version in your workflow. Feel free to open new issue, if you still have a problems with ordering of PR or whatever! :v:
