### ISSUE TITLE
since_tag with unreleased tag unexpected behavior

### ISSUE THREAD

**Issue by lttb** [skywinder/github-changelog-generator#604]
Hi! Thank you a lot for this tool.

I faced with this kind of problem when you set a `since_tag` that has not been released yet.
It starts to generate changes from the first tag then.

It looks like that we don't need to generate anything if that tag is unreleased/undefined

**Comment by hunner** [comment]
It appears that this is the intended behavior dating all the way back to when `--since-tag` was introduced in 32f4df57
It does seem that it is not useful to continue to generate the *entire* changelog because a tag is missing. Only a warning is raised currently; perhaps it should error instead.
