### ISSUE TITLE
Updating to v1.15.0-rc requires --user and --project

### ISSUE THREAD

**Issue by TAGC** [skywinder/github-changelog-generator#633]
I initially installed the latest stable version of this library (v1.14.3) and was able to have it automatically figure out my username and project. However, after updating to the v1.15.0-rc, running it generates the following output:

```
$ github_changelog_generator
Configure which user and project to work on.
Options --user and --project, or settings to that effect. See --help for more.
Usage: github_changelog_generator --user USER --project PROJECT [options]
```

Is it now a requirement to explicitly specify these things, or did I do something wrong?

**Comment by olleolleolle** [comment]
@TAGC You're right, this is a feature that got removed. 

For the GitHub project `weyland-yutani/alien-species-test1`, the invocation is:

```
$ github_changelog_generator --user weyland-yutani --project alien-species-test1
```

**Comment by olleolleolle** [comment]
(You can use the file-based configuration to store these settings, too.)

**Comment by TAGC** [comment]
Ah okay, thanks.

**Comment by hunner** [comment]
For reference #451
