### ISSUE TITLE
Support  change log for specific branch

### ISSUE THREAD

**Issue by skywinder** [skywinder/github-changelog-generator#66]
This change log not works well with complicated git repos (like https://github.com/vanilla/vanilla )
So it's need to add ability to specify branch and check, that PR is included in that branch.
More info: https://github.com/vanilla/vanilla/pull/2553

**Comment by pedelman** [comment]
This would be really useful +1 on this from me

**Comment by skywinder** [comment]
@pedelman I don't know how to check, if issue belong to specific branch or not. 

It's possible not resolve it manually, by set some specific tag for issues and specify them, when you are run script with options:

    --exclude-labels x,y,z
    --include-labels x,y,z

But how to automatically check, in which branch some issue was fixed - I have no idea yet.
If you know some ways to implement it - please, let me know.

**Comment by skywinder** [comment]
Since this project designed to work in github workflow, there is very hard to support custom branches. In general, it uses default branch, that you can specify in the settings of the repo.
If you would like to filter issues by branch - you have to manually set labels for this issues and filter them by options: `--exclude-labels & --include-labels`
