### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by pietbrauer** [skywinder/Github-Changelog-Generator#68]
Currently it is only possible for GitHub.com but it should also be able to use GitHub Enterprise.

Is something like this planned?

**Comment by skywinder** [comment]
@pietbrauer It also compatible with Enterprise!
Check PR #42

There is 2 keys, that you need:
>--github-site [URL]          The Enterprise Github site on which your project is hosted.
    --github-api [URL]           The enterprise endpoint to use for your Github API.

Or run `github_changelog_generator --help` for more info

**Comment by pietbrauer** [comment]
Ah nice, might be useful to add it to the README :+1:

**Comment by skywinder** [comment]
Done, add section to "Features and advantages of this project". Thanks!
