### ISSUE TITLE
Exclude closed (not merged) PR's from changelog.

### ISSUE THREAD

**Issue by skywinder** [skywinder/github-changelog-generator#69]
As @jspahrsummers mention in https://github.com/Mantle/Mantle/pull/468#issuecomment-82070778

This is special PR to test it: https://github.com/skywinder/changelog_test/pull/6

**Comment by monfresh** [comment]
Thanks for this great gem! I just tried it for the first time with 1.3.11, and I'm still seeing this bug. For example, it included this PR, which was closed without being merged: https://github.com/codeforamerica/ohana-api/issues/261

**Comment by monfresh** [comment]
Ah, I see. It's because of the `enhancement` label. Looks like the fix didn't take into account PRs with labels, or with the `enhancement` label.

**Comment by skywinder** [comment]
@monfresh Thanks for notice It!
